// Generated by scripts/gen-command-reference.mjs. Do not edit manually.
// Regenerate via `npm run command-reference`.
export const PUBLIC_COMMAND_LIST =
  "@gittensory help\n@gittensory ask\n@gittensory preflight\n@gittensory blockers\n@gittensory duplicate-check\n@gittensory miner-context\n@gittensory next-action\n@gittensory reviewability\n@gittensory repo-fit\n@gittensory packet";

export const MAINTAINER_COMMAND_LIST =
  "@gittensory queue-summary\n@gittensory confirmed-miners\n@gittensory review-now\n@gittensory needs-author\n@gittensory duplicate-clusters\n@gittensory burden-forecast\n@gittensory intake-health\n@gittensory outcome-patterns\n@gittensory noise-report";
